# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug1
    color: CC0000
  - name: feature
    color: 336699
  - name: first-timers-only
    # include the old name to rename and existing label
    oldname: Help Wanted
