theme: jekyll-theme-minimal
title: Magma MES Division
description: Magma Group is a leading MES solutions provider
github_username: magmagroup


navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
